### ISSUE TITLE
Are you still maintaining this repo?

### ISSUE THREAD

**Issue by subhojit777** [technosophos/drupal-snippets#2]
I was thinking of adding Drupal 8 snippets. Let me know if you are maintaining this repo.

**Comment by subhojit777** [comment]
@technosophos ping.

**Comment by technosophos** [comment]
I am not. If you're interested in continuing development on it, I'd be happy to grant you maintainer privileges!

**Comment by subhojit777** [comment]
That'd be great. Please grant me maintainer priviliges. Thank you.
